In [1]:
# sum function 
import numpy as np 
arr = np.array([10,20,30,40,50])
sum = np.sum(arr)
print("the sum of the array is:",sum)

the sum of the array is: 150


In [2]:
#max function 
import numpy as np 
arr = np.array([10,20,30,40,50])
max = np.max(arr)
print(max)

50


In [3]:
#minfunction 
import numpy as np
arr = np.array([10,20,30,40,50])
min = np.min(arr)
print(min)

10


In [6]:
# mean  function 
import numpy as np
arr = np.array([10,20,30,40,50])
mean= np.mean(arr)
print(mean)

30.0


In [8]:
# median function 
import numpy as np 
arr = np.array([10,20,30,40,50,60])
median = np.median(arr)
print(median)

35.0


In [10]:
# standard deviation  function 
import numpy as np 
arr = np.array([10,20,30,40,30,60])
standard_deviation = np.std(arr)
print(standard_deviation )

15.723301886761007


In [11]:
# variance function 
import numpy as np 
arr = np.array([10,20,30,40,30,60])
variance  = np.var(arr)
print(variance)

247.22222222222226


In [13]:
#  co variance function 
import numpy as np 
arr = np.array([10,20,30,40,30,60])
co_variance  = np.cov(arr)
print(co_variance)

296.6666666666667


In [4]:
# insert 
#np.insert(array_name , index , value , axis )
# axis = 0 (rows)
# axis = 1 (column)
# axis = none 

# for 1d array 

import numpy as np 
arr = np.array([1,2,3,4,5])
new_arr = np.insert(arr,2,10,axis = None)
print(new_arr)
new_arr1 = np.insert(arr,2,10,axis = 0)
print(new_arr1)
#new_arr2 = np.insert(arr,2,10,axis = 1)( we can't use axis = 1 in 1d array)
#print(new_arr2)



[ 1  2 10  3  4  5]
[ 1  2 10  3  4  5]


In [14]:
# insert for 2d array 

import numpy as np
arr = np.array([[1,2],[4,5]])
new_arr = np.insert(arr , 2 , [10,11], axis = None)
print(new_arr)
new_arr1 = np.insert(arr , 2 , [10,11] , axis = 1)
print(new_arr1)
new_arr2 = np.insert(arr , 2 , [10,11], axis = 0)
print(new_arr2)

[ 1  2 10 11  4  5]
[[ 1  2 10]
 [ 4  5 11]]
[[ 1  2]
 [ 4  5]
 [10 11]]


In [15]:
# append 

import numpy as np 
arr = np.array([10,20,30,40])
new_array = np.append(arr , [50,60,70,80,90])
print(new_array)

[10 20 30 40 50 60 70 80 90]


In [5]:
# concatenation
# 1d array

import numpy as np 
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr3 = np.array([9,10,11,12])
new_arr = np.concatenate((arr1 , arr2 , arr3) ,axis= 0)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
#2d array 

import numpy as np 
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
new_arr1 = np.concatenate((arr1,arr2), axis = 0)
print(new_arr1)
new_arr2 = np.concatenate((arr1,arr2), axis = 1)
print(new_arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]


In [7]:
#delete 

import numpy as np 
arr1 = np.array([[1,2,3],[4,5,6]])
new_arr1 = np.delete(arr1 , 1 , axis= 0)
new_arr2 = np.delete(arr1 , 1 , axis= 1)
print(new_arr1)
print(new_arr2)


[[1 2 3]]
[[1 3]
 [4 6]]


In [9]:
# stacking means merging two arrays
# v stacking means vertical stacking - rowwise merge the arrays 
# h stacking means horizontal stacking - columnwise merge the arrays 

import numpy as np 
arr1 = np.array([1,2,3])
arr2 = np.array([8,9,7])
new_arr1 = np.vstack((arr1, arr2))
new_arr2 = np.hstack((arr1, arr2))
print(new_arr1)
print(new_arr2)



[[1 2 3]
 [8 9 7]]
[1 2 3 8 9 7]


In [21]:
# splitting 
#hsplit
#vsplit
# split and h split work same 
import numpy as np
arr = np.array([[10,20,30],[40,50,60],[70,80,90] , [100,110,120]])
split_arr3= np.vsplit(arr , 2)
print(split_arr3)


[array([[10, 20, 30],
       [40, 50, 60]]), array([[ 70,  80,  90],
       [100, 110, 120]])]


In [1]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90,100,110,120])
split_arr3= np.hsplit(arr , 2)
print(split_arr3)


[array([10, 20, 30, 40, 50, 60]), array([ 70,  80,  90, 100, 110, 120])]
