In [1]:
print("hello kashish")

hello kashish


In [4]:
import numpy as np 
python_list = [1,2,3,4,5,6,7,8]
print(python_list)

numpy_array = np.array([1,2,3,4,5,6,7,8])
print(numpy_array)

[1, 2, 3, 4, 5, 6, 7, 8]
[1 2 3 4 5 6 7 8]


In [6]:
# 1-d array 
import numpy as np 
oned_array = np.array([1,2,3,4,5,6])
print(oned_array)

[1 2 3 4 5 6]


In [19]:
# 2 D aaray 
import numpy as np 
arr_2D = np.array([[1,2,3],[4,6,9] ,[3,5,7]])
print(arr_2D)

[[1 2 3]
 [4 6 9]
 [3 5 7]]


In [20]:
# multi demensional array 
import numpy as np 
matrix = np.array([[1,1,2,34,4],[2,3,4,5,6],[8,9,9,6,4],[4,5,3,2,3]])
print(matrix)

[[ 1  1  2 34  4]
 [ 2  3  4  5  6]
 [ 8  9  9  6  4]
 [ 4  5  3  2  3]]


In [21]:
# zeros function 
import numpy as np 
arr_zeros = np.zeros((2,4))
print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
# ones function 
import numpy as np 
arr_ones = np.ones((6,6))
print(arr_ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [24]:
# full function 
import numpy as np 
arr_full = np.full((3,3) , 5)
print(arr_full)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [26]:
# arange function work same as range function 
import numpy as np 
arange = np.arange(1,10)
print(arange)
arange1 = np.arange(2,20,2)
print(arange1)

[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]


In [27]:
# creating identity matrix 
# by using eye function 
import numpy as np 
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
# size  function ( use for finding the size of array)
import numpy as np 
arr = np.array([[1,2,3],[6,7,9],[8,0,7]])
size = arr.size 
print(arr)
print("the size of array is:", size)

[[1 2 3]
 [6 7 9]
 [8 0 7]]
the size of array is: 9


In [31]:
# shape function ( use for finding the shape of array)
import numpy as np
arr = np.array([[2,4,7],[7,9,8],[2,3,4]])
shape = arr.shape
print(arr)
print(" the shape of array is:", shape)

[[2 4 7]
 [7 9 8]
 [2 3 4]]
 the shape of array is: (3, 3)


In [36]:
# ndim function ( use for finding the number of dimensions)
import numpy as np 
arr = np.array([[2,3,4],[5,7,9],[9,4,6],[4,98,8]])
ndim = arr.ndim
print(ndim)

2


In [39]:
# dtype function ( use to find the type of the array )
import numpy as np 
arr = np.array([123, 23, 34.3 ,True])
print(arr)
type = arr.dtype
print("the type of array:" , type)

[123.   23.   34.3   1. ]
the type of array: float64


In [41]:
# astype function (use to convert one data type to another data type
import numpy as np 
arr = np.array([23, 34.2,123])
print(arr)
print(arr.dtype)
new_arr = arr.astype(str)
print(new_arr)
print(new_arr.dtype)


[ 23.   34.2 123. ]
float64
['23.0' '34.2' '123.0']
<U32
