In [4]:
# using list 
prices = [100,200,300]
discount = 10 
new_prices = []
for price in prices:
    new_price  = price - (price*discount/100)
    new_prices.append(new_price)
print(new_prices)

[90.0, 180.0, 270.0]


In [5]:
# by using numpy 
import numpy as np 
price = np.array([100,200,300,400])
discount = 10
new_price = price - (price*discount/100)
print(new_price)

[ 90. 180. 270. 360.]


In [6]:
import numpy as np 
arr = np.array([10,20,30,40,50])
new_arr = arr +2
print(new_arr)


[12 22 32 42 52]


In [8]:
import numpy as np 
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([10,20,30,40,50])
new_arr = arr1 +arr2
new_arr1 = arr1 -arr2
new_arr2 = arr1 *arr2
new_arr3 = arr1 /arr2
print(new_arr)
print(new_arr1)
print(new_arr2)
print(new_arr3)



[ 20  40  60  80 100]
[0 0 0 0 0]
[ 100  400  900 1600 2500]
[1. 1. 1. 1. 1.]


In [9]:
import numpy as np 
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([10])
new_arr = arr1 +arr2
new_arr1 = arr1 -arr2
new_arr2 = arr1 *arr2
new_arr3 = arr1 /arr2
print(new_arr)
print(new_arr1)
print(new_arr2)
print(new_arr3)


[20 30 40 50 60]
[ 0 10 20 30 40]
[100 200 300 400 500]
[1. 2. 3. 4. 5.]


In [10]:
import numpy as np 
arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = np.array([[10,20,30],[40,50,60]])
new_arr = arr1 +arr2
new_arr1 = arr1 -arr2
new_arr2 = arr1 *arr2
new_arr3 = arr1 /arr2
print(new_arr)
print(new_arr1)
print(new_arr2)
print(new_arr3)


[[ 20  40  60]
 [ 80 100 120]]
[[0 0 0]
 [0 0 0]]
[[ 100  400  900]
 [1600 2500 3600]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = np.array([10,20,30])
new_arr = arr1 +arr2
new_arr1 = arr1 -arr2
new_arr2 = arr1 *arr2
new_arr3 = arr1 /arr2

print(new_arr)
print(new_arr1)
print(new_arr2)
print(new_arr3)



[[20 40 60]
 [50 70 90]]
[[ 0  0  0]
 [30 30 30]]
[[ 100  400  900]
 [ 400 1000 1800]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [17]:
arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = np.array([10,20])
new_arr = arr1 +arr2
new_arr1 = arr1 -arr2
new_arr2 = arr1 *arr2
new_arr3 = arr1 /arr2

print(new_arr)
print(new_arr1)
print(new_arr2)
print(new_arr3)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 