In [2]:
# indexing in array 
# for 1d aaray we use arr_name[index]

import numpy as np 
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])
print(arr[-1])

10
30
50


In [5]:
# indexing in array
# for multi dimentional array we use arr_name[row,column]

import numpy as np 
arr = np.array([[12,34,21,45],[23,67,87,90],[23,45,43,67]])
print(arr)
print(arr[2,1])
print(arr[0,2])


[[12 34 21 45]
 [23 67 87 90]
 [23 45 43 67]]
45
21


In [6]:
# slicing in array 

import numpy as np 
arr = np.array([10,20,30,40,50,60])
print(arr[0:6:2])
print(arr[1:4])
print(arr[3:])
print(arr[:6])
print(arr[ : :-1])

[10 30 50]
[20 30 40]
[40 50 60]
[10 20 30 40 50 60]
[60 50 40 30 20 10]


In [7]:
# fancy indexing (selecting the multiple indexing at once )
# list ke form mai index dete h 
import numpy as np 
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr[[0,2,4,5,6,7,]])

[10 30 50 60 70 80]


In [11]:
# boolean masking or filtering 
import numpy as np 
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr[arr>20] )

[30 40 50 60 70 80 90]


In [12]:
# reshaping array 
# it does not create copy 

import numpy as np 
arr = np.array([10,20,30,40,50,60,70,80,90,100])
reshape_arr = arr.reshape(5,2)
print(arr)
print(reshape_arr)

[ 10  20  30  40  50  60  70  80  90 100]
[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


In [2]:
# flattering ( convert 2d array to 1d array)
# ravel - view(changes will going to see in original array )
# flatten - copy(changes will going to see in original array)

import numpy as np 
arr = np.array([[1,2,3,4],[6,7,8,9]])
print(arr.flatten())
print(arr.ravel())


[1 2 3 4 6 7 8 9]
[1 2 3 4 6 7 8 9]
