In [5]:
# mathmatical function (+,-,*,/,//,%,**)
import numpy as np 
arr = np.array([10,20,30,40,50])
print(arr)
new_arr1 = arr+5
print(new_arr1)
new_arr2 = arr-5
print(new_arr2)
new_arr3 = arr*5
print(new_arr3)
new_arr4 = arr/5
print(new_arr4)
new_arr5 = arr//5
print(new_arr5)
new_arr6= arr**2
print(new_arr6)
new_arr7 = arr%2
print(new_arr7)

[10 20 30 40 50]
[15 25 35 45 55]
[ 5 15 25 35 45]
[ 50 100 150 200 250]
[ 2.  4.  6.  8. 10.]
[ 2  4  6  8 10]
[ 100  400  900 1600 2500]
[0 0 0 0 0]
