In [ ]:
'''
three built function to handle missing values
1 - np.isnan : find the mising value 
2- np.nan_to_num : replace mising value to number you will give 
3- np.isinf : check the infinity 

inf = infinity 
nan = not a number 
they result in boolean value and we can't camparen two nan value 

'''

In [2]:
# np.isnan
import numpy as np 
arr = np.array([1,2,np.nan , 4 , np.nan , np.nan ,5,6,7,np.nan])
print(arr)
missing_value = np.isnan(arr)
print(missing_value)

[ 1.  2. nan  4. nan nan  5.  6.  7. nan]
[False False  True False  True  True False False False  True]


In [3]:
# np.nan_to_num 
import numpy as np
arr = np.array([1,2,np.nan , 4 , np.nan , np.nan ,5,6,7,np.nan])
cleaned_arr1 = np.nan_to_num (arr )
cleaned_arr2 = np.nan_to_num (arr , nan= 100)
print(cleaned_arr1)
print(cleaned_arr2)

[1. 2. 0. 4. 0. 0. 5. 6. 7. 0.]
[  1.   2. 100.   4. 100. 100.   5.   6.   7. 100.]


In [4]:
# np.isinf

import numpy as np 
arr = np.array([1,2,3 ,np.inf , 5 , -np.inf ])
bol=  np.isinf(arr)
print(bol)

[False False False  True False  True]


In [7]:
#replacing the infinity value 

import numpy as np 
arr = np.array([1,2,3 ,np.inf , 5 , -np.inf ])
cleaned_arr = np.nan_to_num(arr , posinf = 100 ,neginf = -100)
print(cleaned_arr)


[   1.    2.    3.  100.    5. -100.]
