In [4]:
list1= [1,2,3,4]
list2 = [1,2,3,4]
result  = [x+y for x,y in zip(list1 , list2)]
print(result)


[2, 4, 6, 8]


In [5]:
import numpy as np 
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
result = arr1 +arr2 
print(result)

[2 4 6 8]


In [7]:
import numpy as np 
arr1 = np.array([[1,2,3,4] , [5,6,7,8]])
arr2 = np.array([1,2,3,4])
result = arr1 +arr2 
print(result)

[[ 2  4  6  8]
 [ 6  8 10 12]]


In [8]:
import numpy as np 
arr1 = np.array([[1,2,3,4] , [5,6,7,8]])
arr2 = np.array([[1,2,3,4] , [5,6,7,8]])
result = arr1 +arr2 
print(result)

[[ 2  4  6  8]
 [10 12 14 16]]
